name: Generate and Zip Website

env:
  WC_HUGO_VERSION: '0.123.3'

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "website"
  cancel-in-progress: false

jobs:
  # Build website
  build:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch history for Hugo's .GitInfo and .Lastmod
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true
      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache_runner/
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          echo "Hugo Cache Dir: $(hugo config | grep cachedir)"
          hugo --minify
      - name: Zip artifact
        run: |
          zip -r website.zip ./public
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./website.zip

      - name: Insert Baidu Site Verification Meta Tag
        run: |
          sed -i 's|<head>|<head>\n<meta name="baidu-site-verification" content="codeva-RatOJrEmaq" />|' public/index.html

      - name: Generate file list and add noindex meta tag
        run: |
          # Get all .html and .pdf files in the 'pages' directory
          echo "<!DOCTYPE html>" > public/slidy/index.html
          echo "<html><head><title>Page List</title><meta name=\"robots\" content=\"noindex\"></head><body><h1>List of Pages</h1><ul>" >> public/slidy/index.html
          
          # Loop over each HTML file and add a link to it
          for file in $(ls public/slidy/*.html); do
            if ! grep -q '<meta name="robots" content="noindex">' "$file"; then
              sed -i 's|<head>|<head><meta name="robots" content="noindex">|' "$file"
            fi
            filename=$(basename "$file" .html)
            if [ "$filename" != "index" ]; then
              echo "<li><a href='$filename.html' target='_blank'>$filename</a></li>" >> public/slidy/index.html
            fi
          done

          # Loop over each PDF file and add a link to it if PDFs are present
          for pdf_file in public/slidy/*.pdf; do
            if [ -f "$pdf_file" ]; then
              pdf_filename=$(basename "$pdf_file")
              echo "<li><a href='$pdf_filename' target='_blank'>$pdf_filename</a></li>" >> public/slidy/index.html
            fi
          done

          echo "</ul></body></html>" >> public/slidy/index.html
      - name: Generate README.md
        run: |
          # 生成 README.md 内容（示例为静态内容）
          echo '# [社会认知与人格实验室|林闻正](https://www.linwz.com "社会认知与人格实验室|林闻正") (https://www.linwz.com) 的静态站点文件' > public/README.md
          echo "此仓库为自动生成的静态站点文件，请勿手动修改。" >> public/README.md
          echo "最后更新于: $(date '+%Y-%m-%d %H:%M:%S')" >> public/README.md


# The old modification would not be deleted in this action
#      - name: Deploy
#        uses: manzoorwanijk/action-deploy-to-repo@v3
#        with:
#          src_dir: /public
#          target_repo: lin-wenzheng/linwz.com-static
#          target_dir: /
#          target_branch: main # default
#          access_token: ${{ secrets.GH_TOKEN }}
#          cleanup_command: "rm -rf assets/*" #remove all the files before deploying
#
#          #destination-repository: 'static_website'
#          #destination-directory: '/'
#          git_user_email: 'linlinlin1992@sina.com'

      - name: deploy changes to a repo
        uses: tagus/git-deploy@v0.5.0
        with:
          changes: public
          repository: git@github.com:lin-wenzheng/linwz.com-static.git
          ssh_key: ${{ secrets.DEPLOY_KEY }}
          name: lin-wenzheng
          email: wenzheng.lin@hotmail.com
          clean_repo: true
